testing

diff --git a/.github/actions/install-windsorcli/action.yaml b/.github/actions/install-windsorcli/action.yaml
--- a/.github/actions/install-windsorcli/action.yaml
+++ b/.github/actions/install-windsorcli/action.yaml
@@ -140,6 +140,25 @@ runs:
 
         # Add the Windsor CLI install folder to the GitHub path
         echo "${{ inputs.windsorcli_install_folder }}" >> $GITHUB_PATH
+
+        echo "WINDSOR_PROJECT_ROOT=${{ github.workspace }}" >> $GITHUB_ENV
+
+        windsor init local
+
+        # Run the Windsor env command and capture the output
+        windsor_env_output=$("${{ inputs.windsorcli_install_folder }}/windsor" env)
+
+        # Check if the command was successful
+        if [ $? -ne 0 ]; then
+          echo "Failed to run the Windsor env command."
+          exit 1
+        fi
+
+        # Parse the output and add it to $GITHUB_ENV
+        while IFS= read -r line; do
+          echo "$line" >> $GITHUB_ENV
+        done <<< "$windsor_env_output"
+
       shell: bash
 
     # Install Windsor CLI on Windows
@@ -283,6 +302,12 @@ runs:
         Add-Content -Path $env:GITHUB_PATH -Value "${{ inputs.windsorcli_install_folder }}"
       shell: powershell
 
+    # echo $GITHUB_ENV
+    - name: Print GITHUB_ENV
+      run: |
+        echo $GITHUB_ENV
+      shell: bash
+      
     # Set the WINDSOR_PROJECT_ROOT environment variable
     # - name: Set WINDSOR_PROJECT_ROOT
     #   run: |
