Checking go dependency

diff --git a/.github/actions/windsorcli/action.yaml b/.github/actions/windsorcli/action.yaml
--- a/.github/actions/windsorcli/action.yaml
+++ b/.github/actions/windsorcli/action.yaml
@@ -23,6 +23,29 @@ runs:
   using: 'composite'
   steps:
 
+      # Install Aqua
+    - name: Install Aqua on Linux/macOS
+      if: ${{ matrix.runner.os == 'Linux' || matrix.runner.os == 'macOS' }}
+      uses: aquaproj/aqua-installer@e2d0136abcf70b7a2f6f505720640750557c4b33 # v3.1.1
+      with:
+        aqua_version: v2.28.0
+
+    - name: Set aqua path
+      if: ${{ matrix.runner.os == 'Linux' || matrix.runner.os == 'macOS' }}
+      run: |
+        echo "${AQUA_ROOT_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/aquaproj-aqua}/bin" >> $GITHUB_PATH
+
+    # Install Go
+    - name: Install Go
+      run: |
+        aqua i golang/go@go1.23.4
+
+    # Install Docker
+    - name: Install Docker
+      if: runner.os == 'Windows'
+      run: |
+        aqua i docker/docker@25.0.7
+
     # Install Windsor CLI on Linux/macOS
     - name: Install the Windsor CLI on Linux/macOS
       if: runner.os == 'Linux' || runner.os == 'macOS'
@@ -138,22 +161,22 @@ runs:
 
         export WINDSOR_PROJECT_ROOT=${{ github.workspace }}
         
-        # "${{ inputs.install_folder }}/windsor" init ${{ inputs.context }}
+        "${{ inputs.install_folder }}/windsor" init ${{ inputs.context }}
 
-        # # Run the Windsor env command and capture the output
-        # windsor_env_output=$("${{ inputs.install_folder }}/windsor" env)
+        # Run the Windsor env command and capture the output
+        windsor_env_output=$("${{ inputs.install_folder }}/windsor" env)
 
-        # # Check if the command was successful
-        # if [ $? -ne 0 ]; then
-        #   echo "Failed to run the Windsor env command."
-        #   exit 1
-        # fi
+        # Check if the command was successful
+        if [ $? -ne 0 ]; then
+          echo "Failed to run the Windsor env command."
+          exit 1
+        fi
 
-        # # Parse the output and add it to $GITHUB_ENV
-        # while IFS= read -r line; do
-        #   # Remove 'export ' from the beginning of each line
-        #   echo "${line#export }" >> $GITHUB_ENV
-        # done <<< "$windsor_env_output"
+        # Parse the output and add it to $GITHUB_ENV
+        while IFS= read -r line; do
+          # Remove 'export ' from the beginning of each line
+          echo "${line#export }" >> $GITHUB_ENV
+        done <<< "$windsor_env_output"
 
       shell: bash
 
