Checking go dependency

diff --git a/.github/actions/windsorcli/action.yaml b/.github/actions/windsorcli/action.yaml
--- a/.github/actions/windsorcli/action.yaml
+++ b/.github/actions/windsorcli/action.yaml
@@ -22,6 +22,7 @@ inputs:
 runs:
   using: 'composite'
   steps:
+
     # Install Windsor CLI on Linux/macOS
     - name: Install the Windsor CLI on Linux/macOS
       if: runner.os == 'Linux' || runner.os == 'macOS'
@@ -137,22 +138,22 @@ runs:
 
         export WINDSOR_PROJECT_ROOT=${{ github.workspace }}
         
-        "${{ inputs.install_folder }}/windsor" init ${{ inputs.context }}
+        # "${{ inputs.install_folder }}/windsor" init ${{ inputs.context }}
 
-        # Run the Windsor env command and capture the output
-        windsor_env_output=$("${{ inputs.install_folder }}/windsor" env)
+        # # Run the Windsor env command and capture the output
+        # windsor_env_output=$("${{ inputs.install_folder }}/windsor" env)
 
-        # Check if the command was successful
-        if [ $? -ne 0 ]; then
-          echo "Failed to run the Windsor env command."
-          exit 1
-        fi
+        # # Check if the command was successful
+        # if [ $? -ne 0 ]; then
+        #   echo "Failed to run the Windsor env command."
+        #   exit 1
+        # fi
 
-        # Parse the output and add it to $GITHUB_ENV
-        while IFS= read -r line; do
-          # Remove 'export ' from the beginning of each line
-          echo "${line#export }" >> $GITHUB_ENV
-        done <<< "$windsor_env_output"
+        # # Parse the output and add it to $GITHUB_ENV
+        # while IFS= read -r line; do
+        #   # Remove 'export ' from the beginning of each line
+        #   echo "${line#export }" >> $GITHUB_ENV
+        # done <<< "$windsor_env_output"
 
       shell: bash
 
