Added context check

diff --git a/.github/actions/windsorcli/action.yaml b/.github/actions/windsorcli/action.yaml
--- a/.github/actions/windsorcli/action.yaml
+++ b/.github/actions/windsorcli/action.yaml
@@ -150,41 +150,38 @@ runs:
 
         export WINDSOR_PROJECT_ROOT=${{ github.workspace }}
 
-        # Get the current context
-        current_context=$("${{ inputs.install_folder }}/windsor" context get)
+        # Set the context
+        # Check if the desired context has been initialized by looking for the context in the contexts folder
+        if [ -d "${{ inputs.install_folder }}/contexts/${{ inputs.context }}" ]; then
+          echo "Context ${{ inputs.context }} already initialized."
+          "${{ inputs.install_folder }}/windsor" context set "${{ inputs.context }}"
+        else
+          echo "Context ${{ inputs.context }} not initialized. Initializing..."
+          "${{ inputs.install_folder }}/windsor" init "${{ inputs.context }}"
+        fi
 
-        echo "Current context: $current_context"
-        
-      #   # Check if the current context is available
-      #   if [[ $current_context == *"Error"* ]]; then
-      #     echo "No context is available. Initializing context..."
-      #     "${{ inputs.install_folder }}/windsor" init "${{ inputs.context }}"
-      #     # Re-fetch the current context after initialization
-      #     current_context=$("${{ inputs.install_folder }}/windsor" context get)
-      #   fi
+        # Run the Windsor env command and capture the output
+        windsor_env_output=$("${{ inputs.install_folder }}/windsor" env)
 
-      #   # Run the Windsor env command and capture the output
-      #   windsor_env_output=$("${{ inputs.install_folder }}/windsor" env)
+        # Check if the command was successful
+        if [ $? -ne 0 ]; then
+          echo "Failed to run the Windsor env command."
+          exit 1
+        fi
 
-      #   # Check if the command was successful
-      #   if [ $? -ne 0 ]; then
-      #     echo "Failed to run the Windsor env command."
-      #     exit 1
-      #   fi
-
-      #   # Parse the output and add it to $GITHUB_ENV
-      #   while IFS= read -r line; do
-      #     # Add lines that start with 'export' and remove lines that start with 'unset'
-      #     if [[ $line == export* ]]; then
-      #       # Remove 'export ' from the beginning of each line
-      #       echo "${line#export }" >> $GITHUB_ENV
-      #     elif [[ $line == unset* ]]; then
-      #       # Extract the variable name from the unset command
-      #       var_name="${line#unset }"
-      #       # Remove the variable from $GITHUB_ENV
-      #       sed -i "/^$var_name=/d" $GITHUB_ENV
-      #     fi
-      #   done <<< "$windsor_env_output"
+        # Parse the output and add it to $GITHUB_ENV
+        while IFS= read -r line; do
+          # Add lines that start with 'export' and remove lines that start with 'unset'
+          if [[ $line == export* ]]; then
+            # Remove 'export ' from the beginning of each line
+            echo "${line#export }" >> $GITHUB_ENV
+          elif [[ $line == unset* ]]; then
+            # Extract the variable name from the unset command
+            var_name="${line#unset }"
+            # Remove the variable from $GITHUB_ENV
+            sed -i "/^$var_name=/d" $GITHUB_ENV
+          fi
+        done <<< "$windsor_env_output"
       shell: bash
 
     # Install Windsor CLI on Windows
